# Generated by Django 2.0 on 2017-12-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pflege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=15)),
                ('reciever', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=3000)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
